### ISSUE TITLE
grpreg SCAD analysis with missing values possible?

### ISSUE THREAD

**Issue by RBaudier** [pbreheny/grpreg#10]
Is it possible to perform your grpreg SCAD analysis on data sets with missing values? It seemed from the error message I received about # of observations not matching (which went away when I excluded X variables with missing values) that it is a problem. Would you recommend substituting column averages in the place of missing values? The same question applies to an alternate outcome (y) variable I'd like to use which also has missing values for some subjects. Thanks!

**Comment by pbreheny** [comment]
How to deal with missing data is a huge topic that I cannot possibly do justice to in a Github post, but I wouldn't say it affects penalized regression differently than any other regression model.  *Very* broadly speaking, you can handle missing data via:
1. Removing observations with missing values
2. Imputing the missing values (using, e.g., the mean, as you suggest)
3. Multiple imputation (like 2, but accounts for uncertainty with respect to missing values; many packages assist with this, e.g., [mice](https://cran.r-project.org/web/packages/mice/index.html)).

Without knowing anything about your problem, I am reluctant to give advice.  However, if the amount of missing information is small and more of a nuisance than an important aspect of the study that needs to be accounted for, then I often use single imputation (2) as a simple, reasonable, convenient solution.

Regardless, I'm closing this issue as it isn't really a `grpreg` issue, per se.

**Comment by RBaudier** [comment]
Thanks!
