### ISSUE TITLE
Error in title(...) : 'X11_MetricInfo' -955 < 0

### ISSUE THREAD

**Issue by joy1314** [pbreheny/grpreg#13]
when I used plot to draw fit after I ran  fit <- grpreg(X, y, group, penalty="grLasso")
> plot(fit), I got this error.Does anybody know the reason? how to fix it?

**Comment by pbreheny** [comment]
My best guess is that your system is not set up properly to display Greek letters.  Does it work if you submit
```r
plot(fit, xlab="lambda", ylab="beta")
```
At any rate, this is an issue with your graphics/font configuration, not a grpreg issue.
