### ISSUE TITLE
run into error Error in X[, ind, drop = FALSE] : subscript out of bounds

### ISSUE THREAD

**Issue by fenghelian** [pbreheny/grpreg#16]
I provided exact same type of group, x , y as example but kept getting this error. so depressing.

**Comment by pbreheny** [comment]
Can you provide a [reproducible example](http://myweb.uiowa.edu/pbreheny/reproducible.html)?

**Comment by pbreheny** [comment]
Haven't heard anything back, so I'm closing the issue, but if you're able to provide an example, please re-open.
