### ISSUE TITLE
AUC as a loss function in cv.grpreg

### ISSUE THREAD

**Issue by pedro-ribeirosantiago** [pbreheny/grpreg#31]
Hi Patrick Breheny,

Thanks for the excellent package!! I'm using the function **cv.grpreg** but I'd like to use the **"auc"** as the loss function to use for cross-validation (as in package cv.glmnet). Do you think is there a way to implement this?

Cheers,
Pedro

**Comment by pbreheny** [comment]
Yes -- just look at the documentation: `?AUC`.
