### ISSUE TITLE
Variable Importance?

### ISSUE THREAD

**Issue by abhisuri97** [pbreheny/grpreg#32]
I'm unsure if it applies to grouped regression, but is there a way to get a measure of variable importance but at the group level (or some way to get some proxy of that measure)? I'm thinking about something similar to what caret uses when reporting importance for their ML methods.

**Comment by pbreheny** [comment]
Conceptually, yes, you could calculate variable importance measures for groups (e.g., with caret's approach).  As far as implementation, though, I'm not aware of any pre-existing software that does this, so you might have to implement it yourself.
