### ISSUE TITLE
mfdr inference

### ISSUE THREAD

**Issue by pbreheny** [pbreheny/grpreg#34]
Would be nice to add this, as in **ncvreg**.  Ryan Miller has done some work on this.

**Comment by nidimajiabie** [comment]
I cannot find "summary.grpreg()" function in grpreg package, would you please provide relevant links，thank you very much.

**Comment by pbreheny** [comment]
Well, `summary.grpreg()` doesn't exist. That's where there's an open issue here saying `summary.grpreg()` should exist.
