### ISSUE TITLE
`grpreg` loss function inconsistency in Models vignette

### ISSUE THREAD

**Issue by SzymonNowakowski** [pbreheny/grpreg#52]
[Models vignette](https://pbreheny.github.io/grpreg/articles/web/models.html) defines loss function $L(\beta|X,y)$ in the beginning as **the deviance (−2 times the log-likelihood)**. Later, in **Gaussian (linear regression)** section there is a conflicting definition $L(\beta|X,y) = \frac{1}{2}||y-X\beta||^2$. I believe that either 2 or $\frac{1}{2}$ should be removed.

 I have compared the output of `grpreg` and `glmnet` and they are the same, so looking at [`glmnet` objective function for Gaussian families](https://glmnet.stanford.edu/articles/glmnet.html#linear-regression-family-gaussian-default) I believe the second definition is correct and the factor of 2 should be removed from the opening paragraph: instead of **the deviance (−2 times the log-likelihood)** it should read: **the deviance (minus log-likelihood)**.

**Comment by SzymonNowakowski** [comment]
To go deeper with those inconsistencies, there is `fit$loss` variable if fit is a model returned by `grpreg(...)` call. And `fit$loss` is equal to RSS (−2 times the log-likelihood). See the reproducible example below:
```
> library(glmnet)
> library(grpreg)
> data(QuickStartExample)
> x <- QuickStartExample$x
> y <- QuickStartExample$y

> fit<-grpreg(stats::model.matrix(y~., data = data.frame(y=y, x, check.names = TRUE))[,-1, drop=FALSE], y, group = 1:20, penalty="grLasso")
> sum((cbind(rep(1,100),x) %*% fit$beta[,10] - y)^2)   #pure RSS - no factor of 1/2 here !!!
[1] 363.5578
> fit$loss[10]
[1] 363.5578

**Comment by pbreheny** [comment]
Thank you so much for bringing this to my attention -- this was actually a rather pervasive inconsistency throughout the package. You are correct, the loss and the deviance are not the same -- the loss is half the deviance -- but many variables and functions in **grpreg** were not named consistently, and the loss often referred to the deviance, etc. This should all be fixed now, but please let me know if you see anything wrong.

I'm sorry for all the inconsistencies, and for taking so long to address this issue. Thank you again so much for filing an issue!
