### ISSUE TITLE
A question about “group” setting

### ISSUE THREAD

**Issue by Yuanyuan77-wang** [pbreheny/grpreg#57]
Hi, thank you so much for creating this package!
I have a confusion about parameter settings.Suppose I have 3 groups and each group has 2 members,when I use group = 1,1,2,2,3,3,then I can get group-lasso/group-MCP/group-SCAD.I wonder if I use the group=1:6,whether this is equivalent to lasso/MCP/SCAD?

**Comment by pbreheny** [comment]
Yes, they are equivalent!

**Comment by Yuanyuan77-wang** [comment]
> Yes, they are equivalent!

THANK YOU ! Best wishes!
