### ISSUE TITLE
Error Message -  Could not find build tools necessary to build grpreg

### ISSUE THREAD

**Issue by RBaudier** [pbreheny/grpreg#8]
When trying to install grpreg after installing devtools like so:

install.packages("devtools")
devtools::install_github("pbreheny/grpreg")

 I get this error message :

Downloading GitHub repo pbreheny/grpreg@master
from URL https://api.github.com/repos/pbreheny/grpreg/zipball/master
Error: Could not find build tools necessary to build grpreg

Any ideas on what I'm missing here or what I could try to fix it? Thanks in advance.

**Comment by pbreheny** [comment]
grpreg contains c code, which needs to be compiled.  Linux/Mac systems typically come with C compilers, so I'm guessing you're running Windows?  If so, see here:

https://cran.r-project.org/bin/windows/Rtools

You may also wish to read this:

http://robjhyndman.com/hyndsight/building-r-packages-for-windows

This isn't a grpreg-specific issue, though -- lots of packages have C code.  You can also just install from CRAN, which builds and compiles the windows binaries for you.

(this also addresses hadley/devtools#1420)

**Comment by RBaudier** [comment]
Thanks for your help on this issue! I am using a Mac, but this will at least get me looking in the right direction.
